name: Build and analyse

on: pull_request

jobs:
  run:
    strategy:
      matrix:
        os: [macos-12, macos-11]
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Build Xcode scheme
      run: xcodebuild build -workspace default.xcworkspace -scheme MMTabBarView | xcpretty && exit ${PIPESTATUS[0]}
    - name: Analyse Xcode scheme
      run: xcodebuild analyze -workspace default.xcworkspace -scheme MMTabBarView | xcpretty && exit ${PIPESTATUS[0]}
